crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_DY1
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_STtWt   
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_W4                                                                         
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_DY2ext1v1                                                            
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_STtat                                                         
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_WW                                                                        
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_DY2v1                                                                  
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_STtt                                                                
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_WZ                                                              
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_DY3ext1v1                                                       
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_TT2h                                                                
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_Wext1v2                                                              
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_DY3v1
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_TT2l                                                             
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_Wm                                                                   
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_DY4
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_TT2s                                                           
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_Wp                                                            
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_DYext1v1                                                        
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_VBF                                             
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_Wv2                                                   
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_DYv1                                                           
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_VBFH                                                           
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_ZH                                                                   
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_GG                                                                   
#crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_W1
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_ZZ                                                               
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_GGH                                                                   
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_W2                                                                     
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_ttH
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_STtWat                                                                 
crab getoutput -d crab_projects/crab_plots_PileupAnalyzer_W3